safe:      true
permalink: pretty
highlighter: pygments
exclude:   [ README.md, Gemfile ]

site:
  title:  Liffey Valley Athletics Club
  url:    http://new.liffeyvalleyac.com
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
      category: "news"
  -
    scope:
      path: "races"
      type: "posts"
    values:
      layout: "race"
      category: "race"
