permalink: pretty
highlighter: rouge
exclude: [ README.md, CONTRIBUTING.md, LICENSE, Gemfile, Rakefile, scripts/, tests/, vendor/ ]
paginate: 10
paginate_path: "/news/:num"
future: true

site:
  title: Liffey Valley Athletics Club
  url: http://new.liffeyvalleyac.com

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "news"
      category: "news"
  -
    scope:
      path: ""
      type: "races"
    values:
      layout: "race"
      category: "race"
  -
    scope:
      path: ""
      type: "albums"
    values:
      layout: "gallery"
      category: "album"

collections:
  races:
    output: true
  albums:
    output: true
